### ISSUE TITLE
ddp_ex_career does not find beta-binomial in the right place

### ISSUE THREAD

**Issue by finmod** [QuantEcon/QuantEcon.notebooks#21]
Nice re-organisation. 
The distributions module has gone from qe and no declared anywhere else.

**Comment by oyamad** [comment]
@finmod Thank you for letting us know. QuantEcon/QuantEcon.py#224 fixes this.

The notebook still fails at `from quantecon.models import CareerWorkerProblem` in cell [44] under QE v.0.3 where `models` has gone. This is fixed by #23.
