### ISSUE TITLE
Wald_Friedman ipynb issue with @ for python less than 3.5

### ISSUE THREAD

**Issue by finmod** [QuantEcon/QuantEcon.notebooks#22]
In Wald_Friedman_utils.py at line 110, the new matrix multiplication operator @ is used on download from Github. Unfortunately, this produces a syntax error in all python < 3.5.

**Comment by jstac** [comment]
Thanks @finmod .  Do we want to say something systematic about assumptions on all the notebooks?  Or we can add a note at the top of each notebook...

**Comment by finmod** [comment]
By now, quantecon applications and notebooks are running smoothly in anaconda with all pythons less than 3.5. The dot/@ syntax is the only major novelty of py35 and my suggestion is to put an ExceptionError or warning in the few instances where “dot” appears in quantecon code. Something similar to the warning for “import pandas_datareader.data as web” or just the alternative coding to implement:

EJ = curr_dist @ J(tpl_dist) # in python 35 

# EJ = dot(curr_dist, J(tpl_dist)) # all other pythons as a comment to switch lines.

This is pedagogical too on the use of @ in notebooks. Although this example is obvious, other commutative and associative properties of @ have not been illustrated yet.

**Comment by cc7768** [comment]
I'm going to close this now as we have decided to stop supporting anything less than Python 3.5. See [Release Notes](https://github.com/QuantEcon/QuantEcon.py#ver-033-21-july-2016)
