### ISSUE TITLE
RMT3 chapter 11 simulations

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/QuantEcon.notebooks#26]
@albop  and I have been working on polishing up the notebook I wrote for doing some of the perfect foresight experiments found in chapter 11 of RMT3. 

You can find the recent version of the notebook: https://github.com/EconForge/dolo/blob/master/examples/notebooks/rmt3_ch11.ipynb

All the code in this notebook is ready to go. 

We wanted to open up this issue to give others a chance to see the notebook and comment on any of the exposition or presentation.

This should be a pull request, but I didn't open it as one because it is not self-contained. The path to the yaml file is hard coded into the notebook and assume that the notebook is being run from its home in the dolo repository. We will have to think about a way to get around this.

Thanks

cc @jstac @mmcky @cc7768 @thomassargent30

**Comment by sglyon** [comment]
I should also note that the printing of the yaml file in the notebook only looks funny in the github version of it. When I open on [nbviewer](http://nbviewer.jupyter.org/github/EconForge/dolo/blob/master/examples/notebooks/rmt3_ch11.ipynb) everything looks good to me.

**Comment by albop** [comment]
In order to make the notebook self contained, there is an easy solution :
replace the filename by an url when importing the model : `model =
yaml_import('
https://raw.githubusercontent.com/EconForge/dolo/master/examples/notebooks/rmt3_ch11.ipynb').

**Comment by jstac** [comment]
This is really great.  Very cool.  The explanations are very good too.

Some small comments:

At the start of [this section](http://nbviewer.jupyter.org/github/EconForge/dolo/blob/master/examples/notebooks/rmt3_ch11.ipynb#Experiment-1--%28RMT-3-Figure-11.9.1%29) you might mention the fact that you will generate the plot a hard way and then an easy way, so people can skip forward to the easier dolo function if they wish.

Also, some typos:
- "refer an the interested reader"
- cut comma in "separate the model definition, from the code"
- there to here in "available there"
- "hold the socks"  should be shocks ;-)
- "larger an quicker"

**Comment by sglyon** [comment]
@albop good idea. I've implemented this

@jstac thanks for this feedback. I have made all the changes, so if you check out the most recent version of the notebook they should be live.

**Comment by jstac** [comment]
Great.  It's going to be very valuable.  Are you happy for us to put this up?

**Comment by sglyon** [comment]
Unless others have comments on the exposition I think this is ready.

Tom mentioned that it would be good to do some of the international exercises at the end of the chapter, but the computation there is somewhat more involved so it could merit a follow up notebook.

**Comment by jstac** [comment]
@thomassargent30 Are you happy for us to put this up?

**Comment by jstac** [comment]
@spencerlyon2 @mmcky @albop Pablo pointed out last night that we'd forgotten to put this up.  Sorry about that.  No response from TJS but I think we can go ahead.  @spencerlyon2 I assume you're happy for us to put this up now?

**Comment by jstac** [comment]
@spencerlyon2 @mmcky @albop Having looked at the thread I can see @spencerlyon2 is happy with it so I went ahead and put it up.  It might take a day or so to propagate to cloud front.

**Comment by sglyon** [comment]
Looks good to me, thanks!
