### ISSUE TITLE
run ar1_pymc on anaconda 2.5 and windows

### ISSUE THREAD

**Issue by finmod** [QuantEcon/QuantEcon.notebooks#32]
Please note that installing pymc on anaconda 2.5.0 and windows should follow this command:

conda install -c https://conda.binstar.org/pymc pymc

instead of conda install pymc or pip install pymc

Then the notebook runs smootly.

**Comment by jstac** [comment]
@finmod Many thanks.  I changed the instructions to your suggestion since it works on all platforms.
