### ISSUE TITLE
Link to notebook gallery in README is not working

### ISSUE THREAD

**Issue by janosg** [QuantEcon/QuantEcon.notebooks#94]
The link in the following section of the README is not working:

```rst
A curated list of notebooks that draws on the notebooks collected
in this repository is now available `here <http://quantecon.org/notebooks.html>`__
```
The same link also needs to be updated at the bottom of https://quantecon.org/quantecon-py/

The correct link might be: https://mybinder.org/repo/QuantEcon/QuantEcon.notebooks

openjournals/joss-reviews#5585

**Comment by mmcky** [comment]
thanks you @janosg 

This repo is relatively old and should be archived -- I have opened https://github.com/QuantEcon/website/pull/111 to update that page. 

Thank you for your comments and review. It is really helpful.

**Comment by mmcky** [comment]
addressed by https://github.com/QuantEcon/website/pull/111 to update the `org` QuantEcon.py information page.
